name: kilted-binaries-ubuntu-24.04

on:
  workflow_dispatch:

  pull_request:
    branches:
      - kilted
      - main

  push:
    branches:
      - kilted
      - main

  schedule:
    - cron: '0 0 * * *'

jobs:
  ubuntu-install-from-binaries:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || 'kilted'}}
          submodules: 'recursive'

      - name: Install from binaries
        run: |
          bash docs/resources/scripts/linux_binary_installation.bash
